### ISSUE TITLE
Remove-MsBuildProperty does not remove all build property

### ISSUE THREAD

**Issue by fakedevil** [jonwagner/BuildTools.NET#1]
Looking at the PS script, not sure if its intentional, but the Remove-MsBuildProperty does not remove all properties in different property groups. Nor does it seem like it would adhere to the configuration type as suggested by the comments. 

I created 2 similar functions that will return me all of the properties as well as remove it. (I an probably modify the existing one to take a flag but will leave it to you to decide if this is useful)

function Get-MsBuildProperty-Recursive {
    param (
        $Project,
        [string] $Name
    )

```
# make sure we always have an msbuild project
$Project = Get-MsBuildProject -Project $Project

$props = $Project.Xml.PropertyGroups | % Properties
if ($Name) {
    return $props |? Name -eq $Name
}
else {
    return $props
}
```

}

function Remove-MsBuildProperty-Recursive {
    param (
        $Project,
        [Parameter(Mandatory=$true)]
        [string] $Name
    )

```
# make sure we always have an msbuild project
$Project = Get-MsBuildProject -Project $Project

# remove it from all of the matching configurations
Get-MsBuildProperty-Recursive -Project $Project -Name $Name |% {
    $_.Parent.RemoveChild($_) | Out-Null
}
```

}

**Comment by jonwagner** [comment]
You're right - the comments for Remove-MsBuildProperty are entirely wrong.
Also, Get-MsBuildProperty only returns the first matching property. 

Now to figure out why I stopped at one property...

**Comment by jonwagner** [comment]
Get now returns all properties, not just the first group it finds. The caller can then filter as appropriate.
Set now has an option to set the property in -All global property groups (although I don't know how useful that would be.)
