### ISSUE TITLE
BuildTools.Stylecop is not installed at first try.

### ISSUE THREAD

**Issue by itajaja** [jonwagner/BuildTools.NET#2]
Running nuget restore package from my CI ([appveyor](https://ci.appveyor.com/project/itajaja/h-dependency/build/1.0.21)) doesn't seem to load `buildTools.stylecop` and `buildTools.stylecopPlus`. Running it from command line on my machine yields the same error for the first time, but the second runs ok. This problem occurs only with the mentioned `buildtools.*` packages. Any thoughts?

**Comment by itajaja** [comment]
The problem seems to be that it inserts the following target on the csporj files:

``` XML
  <Target Name="___packages_BuildTools_StyleCop_4_7_49_0_tools_StyleCop_targets" Condition="$(StyleCopOutputFile)==''" BeforeTargets="BeforeBuild">
    <Error Text="BuildTools_StyleCop - the BuildTools_StyleCop package has not been restored.&#xD;&#xA;If you are running this from an IDE, make sure NuGet Package Restore has been enabled, then reload the solution and re-run the build.&#xD;&#xA;If you are running this from the command line, run the build again.&#xD;&#xA;If this is a CI server, you may want to make sure NuGet Package Restore runs before your build with:&#xD;&#xA;   msbuild solution.sln /t:restorepackages" />
  </Target>
```

I don't see how this check could be actually beneficial... If package restore is not enabled, you are gonna incur in much bigger problems, not only for stylecop...

**Comment by itajaja** [comment]
It actually kind of "works". For some reason the target is not recognized the first time, so stylecop is not run. I understand the problem, but what can be the solution for my CI? I cannot run it again, because it starts from scratch anyway...

**Comment by jonwagner** [comment]
Old versions of msbuild and nuget didn't always restore packages before executing. I think that if you switch to nuget 2.7 or later and automaticpackagerestore, the problems should go away.

see:
http://docs.nuget.org/docs/workflows/migrating-to-automatic-package-restore
http://blog.davidebbo.com/2014/01/the-right-way-to-restore-nuget-packages.html

**Comment by itajaja** [comment]
Thanks for the tip, I think we can close it (maybe adding it on the README.md)?
cheers
